### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-space-pen-views'

### ISSUE THREAD

**Issue by ohmycloud** [Galadirith/markdown-preview-plus#190]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.6.0
**System**: Mac OS X 10.10.5
**Thrown From**: [markdown-preview-plus](https://github.com/Galadirith/markdown-preview-plus) package, v2.2.2
**User**: root
### Stack Trace

Uncaught Error: Cannot find module 'atom-space-pen-views'

```
At module.js:338

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/Applications/Atom.app/Contents/Resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/Users/chenyf/.atom/packages/markdown-preview-plus/lib/markdown-preview-view.coffee:4:24)
    at Object.<anonymous> (/Users/chenyf/.atom/packages/markdown-preview-plus/lib/markdown-preview-view.coffee:1:1)
    at Module._compile (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/Applications/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Applications/Atom.app/Contents/Resources/app.asar/src/native-compile-cache.js:50:27)
    at isMarkdownPreviewView (/Users/chenyf/.atom/packages/markdown-preview-plus/lib/main.coffee:12:26)
    at Object.module.exports.toggle (/Users/chenyf/.atom/packages/markdown-preview-plus/lib/main.coffee:168:8)
    at atom-workspace.atom.commands.add.markdown-preview-plus:toggle (/Users/chenyf/.atom/packages/markdown-preview-plus/lib/main.coffee:133:10)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:1013:28)
    at emitOne (events.js:77:13)
    at EventEmitter.emit (events.js:169:7)
```
### Commands

```
     -0:28.8.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -0:28.6.0 core:copy (atom-text-editor.editor.is-focused)
     -0:01.5.0 markdown-preview-plus:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "AtomicChar",
      "spell-check",
      "metrics",
      "language-ruby-on-rails",
      "language-ruby",
      "language-objective-c",
      "language-mustache",
      "language-make",
      "language-java",
      "language-go",
      "language-csharp",
      "language-coffee-script",
      "language-clojure",
      "language-c",
      "linter",
      "language-perl",
      "markdown-preview"
    ],
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "markdown-preview-plus": {}
}
```
### Installed Packages

``` coffee
# User
atom-perl6-editor-tools, v0.9.18
autocomplete-swift, v1.0.2
build, v0.57.0
file-icons, v1.6.18
hyperclick, v0.0.35
language-perl6fe, v1.6.1
language-swift, v0.4.0
markdown-preview-plus, v2.2.2
pandoc-convert, v1.0.4
perltidy, v2.2.0
refactor, v0.6.0
script-runner, v1.8.4

# Dev
No dev packages
```

**Comment by lierdakil** [comment]
Package likely failed to install its dependencies. Try removing and reinstalling (if it's still relevant). Bear in mind that running Atom from root in *not* a good idea. I will close this now, but let me know if you're still experiencing issues.
