### ISSUE TITLE
Install failed on ubuntu 14.04 gnome

### ISSUE THREAD

**Issue by myhelloos** [Galadirith/markdown-preview-plus#26]
I'm on ubuntu 14.04 gnome with atom 0.175.0
and followed the steps
```
   1. Download markdown-preview-plus from here and inside that archive file you'll find a folder called markdown-preview-plus-1.2.0. Unpack its contents into ~/.atom/packages/markdown-preview-plus such that you now have folders like:

    ~/.atom/packages/markdown-preview-plus/assets
    ~/.atom/packages/markdown-preview-plus/imgs
    ...

    (alternatively if you are comfortable doing it you could git clone markdown-preview-plus into ~/.atom/packages).
   2. Now open a terminal and move to the directory ~/.atom/packages/markdown-preview-plus
   3. Run npm install
   4. Assuming there are no errors run apm rebuild
    If all went well markdown-preview-plus should now be available in Atom.
```
But, I get failed on step 4; the output says:

```
> oniguruma@4.0.0 install /tmp/apm-install-dir-11527-7167-1aux9j2/node_modules/markdown-preview-plus/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma
> node-gyp rebuild


> runas@2.0.0 install /tmp/apm-install-dir-11527-7167-1aux9j2/node_modules/markdown-preview-plus/node_modules/pathwatcher/node_modules/runas
> node-gyp rebuild


Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-46-generic
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11527-7167-1aux9j2/node_modules/markdown-preview-plus/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
Usage: gyp_main.py [options ...] [build_file ...]

gyp_main.py: error: no such option: --no-parallel
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onCpExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.13.0-46-generic
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11527-7167-1aux9j2/node_modules/markdown-preview-plus/node_modules/pathwatcher/node_modules/runas
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.13.0-46-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/usr/share/atom/resources/app/apm/.apmrc" "--userconfig" "/home/alfred/.atom/.apmrc" "install" "/tmp/d-11527-7167-3z72jg/package.tgz" "--target=0.20.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.1.18
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@4.0.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@4.0.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11527-7167-1aux9j2/npm-debug.log
```

**Comment by Galadirith** [comment]
@myhelloos Thanks for opening an issue, and I'm really sorry your having problems with the last step. Could I ask you to send me the output of `apm -v` and `apm install --check`.

On the surface its looks like that you might have the wrong version of Python installed. To install the package you'll need a `v2.7.X` version installed, you can get hold of the latest version through Ubuntus package manager `sudo apt-get install python2.7` or you can download the source [Python 2.7.9](https://www.python.org/downloads/release/python-279/). If you have another version of Python installed installing another version shouldn't affect it.

Please do let me know how that goes and please msg me back with and questions :D. I apologise in advance I might be unreachable over the next 2 weeks but will reply to any questions as soon as I can :D

**Comment by myhelloos** [comment]
the result for `apm -v` is:
```
apm  0.123.0
npm  2.1.18
node 0.10.35
python 2.7.6
git 1.9.1
```
and the result for `amn install --check` is:
```
Checking for native build tools ✓
```
there are `python 2.7.6

**Comment by Root-nix** [comment]
I have the same issue.

**Comment by keorn** [comment]
If you are getting the error with the Python v2.7.x, then it is probably due to node-gyp confilict with gyp. That fixed it for me.
```sudo apt-get remove gyp```

**Comment by myhelloos** [comment]
it seems that node-gyp depend on gyp:
```
Use 'apt-get autoremove' to remove them.
The following packages will be REMOVED:
  gyp node-gyp npm

```

**Comment by Galadirith** [comment]
@Root-nix @keorn @myhelloos I owe you all a massive apology for my really long absence.

I've just pushed a new (and long over due) update. Its possible that will fix you installation problems, but if not please update me with your issues and we'll take it from there :D

**Comment by Galadirith** [comment]
@myhelloos @Root-nix As its been over a month since my last comment without any reply I hope that you've had success installing MPP. I will close the issue now but if you are still experiencing installation problems please post back and I would be more than happy to look further into the issue :D
