### ISSUE TITLE
Uncaught Error: Module did not self-register.

### ISSUE THREAD

**Issue by rayjanwilson** [Galadirith/markdown-preview-plus#33]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.191.0-3bbf337
**System**: Mac OS X 10.9.5
**Thrown From**: [markdown-preview-plus](https://github.com/Galadirith/markdown-preview-plus) package, v1.3.0

### Stack Trace

Uncaught Error: Module did not self-register.

```
At ATOM_SHELL_ASAR.js:118

Error: Module did not self-register.
  at Error (native)
  at Object.module.(anonymous function) (ATOM_SHELL_ASAR.js:118:20)
  at Object.module.(anonymous function) [as .node] (ATOM_SHELL_ASAR.js:118:20)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/wilsonrm/.atom/packages/markdown-preview-plus/node_modules/pathwatcher/lib/main.js:6:13)
  at Object.<anonymous> (/Users/wilsonrm/.atom/packages/markdown-preview-plus/node_modules/pathwatcher/lib/main.js:207:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (/Applications/Atom.app/Contents/Resources/app/src/babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/Users/wilsonrm/.atom/packages/markdown-preview-plus/lib/markdown-preview-view.coffee:8:10)
  at Object.<anonymous> (/Users/wilsonrm/.atom/packages/markdown-preview-plus/lib/markdown-preview-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/Applications/Atom.app/Contents/Resources/app/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at isMarkdownPreviewView (/Users/wilsonrm/.atom/packages/markdown-preview-plus/lib/main.coffee:11:26)
  at Object.module.exports.toggle (/Users/wilsonrm/.atom/packages/markdown-preview-plus/lib/main.coffee:84:8)
  at atom-workspace.atom.commands.add.markdown-preview-plus:toggle (/Users/wilsonrm/.atom/packages/markdown-preview-plus/lib/main.coffee:46:10)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:242:29)
  at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:157:19)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:73:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -1:35.0 editor:indent (atom-text-editor.editor.is-focused)
     -1:34.7 core:move-down (atom-text-editor.editor.is-focused)
     -1:34.3 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -1:34.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -1:34.0 snippets:expand (atom-text-editor.editor.is-focused)
     -1:34.0 editor:indent (atom-text-editor.editor.is-focused)
     -1:27.8 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -1:27.4 editor:newline (atom-text-editor.editor.is-focused)
  4x -1:27.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:08.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:52.6 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
  2x -0:52.0 core:select-right (atom-text-editor.editor.is-focused)
     -0:33.5 core:save (atom-text-editor.editor.is-focused)
     -0:29.6 markdown-preview-plus:toggle (atom-text-editor.editor.is-focused)
     -0:05.4 markdown-preview-plus:toggle-render-latex (atom-text-editor.editor.is-focused)
     -0:00.8 markdown-preview-plus:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "projectHome": "/Users/wilsonrm/dev/git",
    "disabledPackages": [
      "markdown-preview"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.23.4
coffee-compile, v0.12.0
linter, v0.12.0
markdown-preview-plus, v1.3.0
mathjax-wrapper, v0.1.0

# Dev
No dev packages
```

**Comment by Stephen304** [comment]
I restarted atom after reinstalling MPP and it fixed this.

**Comment by Galadirith** [comment]
Hey @rayjanwilson @Stephen304 I'm really sorry I havn't been able to get back to you sooner.

The uncaught error should be fixed with the latest version of MPP `1.4.0` that I just pushed out. Please let me know if that fixes everything for you :D

**Comment by rayjanwilson** [comment]
cool i'll give it a go. thanks for looking into it.

**Comment by rayjanwilson** [comment]
looks good from my end. thanks =)

**Comment by Galadirith** [comment]
Thats great :D I'll close the issue but if any problems arise please reopen this or open a new issue :D

**Comment by rayjanwilson** [comment]
will do
