### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by hazam** [Galadirith/markdown-preview-plus#37]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.201.0
**System**: Mac OS X 10.10.3
**Thrown From**: [markdown-preview-plus](https://github.com/Galadirith/markdown-preview-plus) package, v1.4.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/emanuele.di.saverio/.atom/packages/markdown-preview-plus/lib/renderer.coffee:34

TypeError: undefined is not a function
  at /Users/emanuele.di.saverio/.atom/packages/markdown-preview-plus/lib/renderer.coffee:34:5
  at /Users/emanuele.di.saverio/.atom/packages/markdown-preview-plus/lib/renderer.coffee:52:5
  at module.exports (/Users/emanuele.di.saverio/.atom/packages/markdown-preview-plus/node_modules/roaster/lib/roaster.js:66:14)
  at render (/Users/emanuele.di.saverio/.atom/packages/markdown-preview-plus/lib/renderer.coffee:47:3)
  at Object.exports.toHTML (/Users/emanuele.di.saverio/.atom/packages/markdown-preview-plus/lib/renderer.coffee:29:3)
  at Object.module.exports.copyHtml (/Users/emanuele.di.saverio/.atom/packages/markdown-preview-plus/lib/main.coffee:135:14)
  at atom-workspace.atom.commands.add.markdown-preview-plus:copy-html (/Users/emanuele.di.saverio/.atom/packages/markdown-preview-plus/lib/main.coffee:48:10)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:238:29)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:159:32)

```

### Commands

```
     -0:05.4.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:01.3.0 markdown-preview-plus:copy-html (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "disabledPackages": [
      "markdown-preview"
    ]
  },
  "markdown-preview-plus": {}
}
```

### Installed Packages

```coffee
# User
markdown-preview-plus, v1.4.0
mathjax-wrapper, v0.1.0

# Dev
No dev packages
```

**Comment by Galadirith** [comment]
@hazam Thanks so much for the bug report and I am sorry it has taken me this long to respond. I'll be fixing the copy feature of MPP shortly and will update you when its published.

**Comment by Galadirith** [comment]
@hazam `Copy As HTML` is now working in the latest release [`v1.6.0`](https://github.com/Galadirith/markdown-preview-plus/releases/tag/v1.6.0). I'll close the issue now but if you have any further problems please post back :D
