### ISSUE TITLE
Uncaught Error: Cannot find module 'pathwatcher'

### ISSUE THREAD

**Issue by valleyrain** [Galadirith/markdown-preview-plus#45]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Unknown Windows Version
**Thrown From**: [markdown-preview-plus](https://github.com/Galadirith/markdown-preview-plus) package, v1.6.0

### Stack Trace

Uncaught Error: Cannot find module 'pathwatcher'

```
At module.js:330

Error: Cannot find module 'pathwatcher'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (C:\Users\valleyrain\AppData\Local\atom\app-1.0.2\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\valleyrain\.atom\packages\markdown-preview-plus\lib\markdown-preview-view.coffee:8:10)
  at Object.<anonymous> (C:\Users\valleyrain\.atom\packages\markdown-preview-plus\lib\markdown-preview-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (C:\Users\valleyrain\AppData\Local\atom\app-1.0.2\resources\app.asar\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at isMarkdownPreviewView (C:\Users\valleyrain\.atom\packages\markdown-preview-plus\lib\main.coffee:11:26)
  at Object.module.exports.toggle (C:\Users\valleyrain\.atom\packages\markdown-preview-plus\lib\main.coffee:149:8)
  at atom-workspace.atom.commands.add.markdown-preview-plus:toggle (C:\Users\valleyrain\.atom\packages\markdown-preview-plus\lib\main.coffee:111:10)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (C:\Users\valleyrain\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:241:29)
  at CommandRegistry.handleCommandEvent (C:\Users\valleyrain\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (C:\Users\valleyrain\AppData\Local\atom\app-1.0.2\resources\app.asar\src\command-registry.js:156:19)
  at EventEmitter.<anonymous> (C:\Users\valleyrain\AppData\Local\atom\app-1.0.2\resources\app.asar\src\window-event-handler.js:70:30)
  at emitOne (events.js:77:13)
  at EventEmitter.emit (events.js:166:7)

```

### Commands

```
     -1:38.5.0 markdown-preview-plus:toggle (div.settings-view.pane-item)
  2x -1:37.4.0 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -1:14.9.0 core:paste (atom-text-editor#markdown-preview-plus.pandocPath.editor.mini.is-focused)
     -1:01.4.0 grammar-selector:show (atom-text-editor.editor)
     -0:51.7.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:51.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:51.4.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:51.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:49.4.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:46.7.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:44.3.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:41.3.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:38.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:09.2.0 bracket-matcher:select-inside-brackets (atom-text-editor.editor.is-focused)
     -0:03.1.0 markdown-preview-plus:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "markdown-preview"
    ]
  },
  "markdown-preview-plus": {
    "pandocPath": "C:\\Users\\valleyrain\\AppData\\Local\\Pandoc",
    "useGitHubStyle": true,
    "enableLatexRenderingByDefault": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.28.7
last-cursor-position, v0.9.0
markdown-preview-plus, v1.6.0
mathjax-wrapper, v0.1.0
minimap, v4.11.2
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.2.0
minimap-highlight-selected, v4.3.0

# Dev
No dev packages
```

**Comment by Galadirith** [comment]
@valleyrain Thanks for the bug report. Since the report have you been able to successfully use MPP? I've also encounter such issues in the past but they have been resolved by reloading atom. Here's the process that I've taken to resolve such issues.

1. **Click on the red bug icon**
There should be a red bug that appears in the bottom right hand corner of atom. Click on it.
![](http://blog.atom.io/img/posts/incompatible-packages-status-bar.png)

2. **Click reload button** 
Click the button that says **Reload Atom And Recheck Packages**
![incompatible-packages](https://cloud.githubusercontent.com/assets/1201875/8651973/e30bc43c-2973-11e5-9999-67a875e4066f.png)

Please let me know how that goes :D

**Comment by valleyrain** [comment]
I didn't find the button and messages in the pictures you posted to me, I open the window and it appears blow.
![1](https://cloud.githubusercontent.com/assets/7576438/8678591/e3642914-2a87-11e5-9c37-d81e429201f5.jpg)

and what's more, I tried to install it again, but there's something wrong like this, I hope you can help me with this.
![2](https://cloud.githubusercontent.com/assets/7576438/8678595/e941b658-2a87-11e5-8b5d-dde343525811.png)

THX a lot!

**Comment by Galadirith** [comment]
Thanks for the update @valleyrain and I'm sorry you've now got another issue. Lets try to work on the installation issue first which might cure the original problem. 

The error you got while attempting to install MPP looks identical to Galadirith/markdown-preview-plus#43. If you have the time you might be able to find a solution reading through that thread. What ended up solving the problem was [installing MPP through git bash](https://github.com/Galadirith/markdown-preview-plus/issues/43#issuecomment-120931220). It looks like right now your using either `cmd` or `powershell` so if you can I would suggest trying out the git bash route.

Please let me know how that goes and then we can take it from there :D
