### ISSUE TITLE
Can't preview if pandoc is activated

### ISSUE THREAD

**Issue by DevWurm** [Galadirith/markdown-preview-plus#82]
[Enter steps to reproduce below:]

1. Install mathjax-wrapper and markdown-preview-plus
2. Activate 'Enable Pandoc Parser'
3. Toggle Preview

**Atom Version**: 1.0.7
**System**: Ubuntu 15.04
**Thrown From**: [markdown-preview-plus](https://github.com/Galadirith/markdown-preview-plus) package, v1.7.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/octoworm/.atom/packages/markdown-preview-plus/lib/update-preview.coffee:73

TypeError: undefined is not a function
    at prepareCodeBlocksForAtomEditors (/home/devwurm/.atom/packages/markdown-preview-plus/lib/update-preview.coffee:63:24)
    at UpdatePreview.module.exports.UpdatePreview.update (/home/devwurm/.atom/packages/markdown-preview-plus/lib/update-preview.coffee:19:7)
    at /home/devwurm/.atom/packages/markdown-preview-plus/lib/markdown-preview-view.coffee:297:35
    at /home/devwurm/.atom/packages/markdown-preview-plus/lib/renderer.coffee:66:14
    at Function.callbackFunction (/home/devwurm/.atom/packages/markdown-preview-plus/lib/renderer.coffee:96:14)
    at handleResponse (/home/devwurm/.atom/packages/markdown-preview-plus/lib/pandoc-helper.coffee:183:28)
    at ChildProcess.<anonymous> (/home/devwurm/.atom/packages/markdown-preview-plus/node_modules/pdc/pdc.js:65:5)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at maybeClose (child_process.js:997:16)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "markdown-preview"
    ]
  },
  "markdown-preview-plus": {
    "enableLatexRenderingByDefault": true,
    "enablePandoc": true
  }
}
```

### Installed Packages

```coffee
# User
markdown-preview-plus, v1.7.0
mathjax-wrapper, v0.1.0

# Dev
No dev packages
```

**Comment by DevWurm** [comment]
After reinstalling it worked

**Comment by Galadirith** [comment]
@DevWurm Thanks for closing the issue. If it resurfaces please let us know :D

**Comment by DevWurm** [comment]
Interestingly ist appears from time to time, but reopening the Markdown view solves the problem :)

**Comment by leipert** [comment]
Maybe it doesn't find the pandoc path sometimes. Try to put the full pandoc path (simply run `which pandoc` in a Terminal) into the settings.
