### ISSUE TITLE
Updating to “markdown-preview-plus@2.0.0” failed

### ISSUE THREAD

**Issue by cprybol** [Galadirith/markdown-preview-plus#90]
when trying to update from MPP 1.7.0 to 2.0.0
on atom 1.0.10
running OS X 10.11 Beta (15A278b) (public beta 6)

```
> fsevents@0.3.8 install /private/var/folders/p5/_x1sy3yx0cnd35c_r9zzgz840000gn/T/apm-install-dir-11582-25889-12pt3lh/node_modules/markdown-preview-plus/node_modules/markdown-it-math/node_modules/ascii2mathml/node_modules/babel/node_modules/chokidar/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node

> pathwatcher-without-runas@4.5.0 install /private/var/folders/p5/_x1sy3yx0cnd35c_r9zzgz840000gn/T/apm-install-dir-11582-25889-12pt3lh/node_modules/markdown-preview-plus/node_modules/pathwatcher-without-runas
> node-gyp rebuild

  CXX(target) Release/obj.target/pathwatcher/src/main.o
  CXX(target) Release/obj.target/pathwatcher/src/common.o
  CXX(target) Release/obj.target/pathwatcher/src/handle_map.o
  CXX(target) Release/obj.target/pathwatcher/src/pathwatcher_mac.o
  SOLINK_MODULE(target) Release/pathwatcher.node

> oniguruma@4.2.2 install /private/var/folders/p5/_x1sy3yx0cnd35c_r9zzgz840000gn/T/apm-install-dir-11582-25889-12pt3lh/node_modules/markdown-preview-plus/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma
> node-gyp rebuild

  CC(target) Release/obj.target/oniguruma/deps/onig/regcomp.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regenc.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regerror.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regexec.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regext.o
  CC(target) Release/obj.target/oniguruma/deps/onig/reggnu.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regparse.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regposerr.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regposix.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regsyntax.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regtrav.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regversion.o
  CC(target) Release/obj.target/oniguruma/deps/onig/st.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/ascii.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/big5.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/cp1251.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_jp.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_kr.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_tw.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/gb18030.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_1.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_2.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_3.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_4.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_5.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_6.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_7.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_8.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_9.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_10.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_11.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_13.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_14.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_15.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_16.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/koi8.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/koi8_r.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/mktable.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/sjis.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/unicode.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf16_be.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf16_le.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf32_be.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf32_le.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf8.o
  LIBTOOL-STATIC Release/oniguruma.a
  CXX(target) Release/obj.target/onig_scanner/src/onig-cache.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-result.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-reg-exp.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-scanner.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-scanner-worker.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-searcher.o
  CXX(target) Release/obj.target/onig_scanner/src/onig-string-context.o
  CXX(target) Release/obj.target/onig_scanner/src/unicode-utils-posix.o
  SOLINK_MODULE(target) Release/onig_scanner.node

npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/p5/_x1sy3yx0cnd35c_r9zzgz840000gn/T/apm-install-dir-11582-25889-12pt3lh/node_modules/markdown-preview-plus/node_modules/markdown-it-math/node_modules/ascii2mathml/node_modules/babel/node_modules/chokidar/node_modules/fsevents
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Release/pathwatcher.node] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 15.0.0
gyp ERR! command "node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /private/var/folders/p5/_x1sy3yx0cnd35c_r9zzgz840000gn/T/apm-install-dir-11582-25889-12pt3lh/node_modules/markdown-preview-plus/node_modules/pathwatcher-without-runas
gyp ERR! node -v v0.10.40
gyp ERR! node-gyp -v v2.0.2
gyp ERR! not ok 
npm WARN optional dep failed, continuing fsevents@0.3.8
npm ERR! Darwin 15.0.0
npm ERR! argv "/Applications/Atom.app/Contents/Resources/app/apm/bin/node" "/Applications/Atom.app/Contents/Resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/Users/Cameron/.atom/.apm/.apmrc" "--userconfig" "/Users/Cameron/.atom/.apmrc" "install" "/private/var/folders/p5/_x1sy3yx0cnd35c_r9zzgz840000gn/T/d-11582-25889-ijgbab/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.40
npm ERR! npm  v2.13.3
npm ERR! code ELIFECYCLE

npm ERR! pathwatcher-without-runas@4.5.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pathwatcher-without-runas@4.5.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pathwatcher-without-runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pathwatcher-without-runas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /private/var/folders/p5/_x1sy3yx0cnd35c_r9zzgz840000gn/T/apm-install-dir-11582-25889-12pt3lh/npm-debug.log
```

When trying to open the above file `/private/var/folders/p5/_x1sy3yx0cnd35c_r9zzgz840000gn/T/apm-install-dir-11582-25889-12pt3lh/npm-debug.log`, the file did not exist

**Comment by Galadirith** [comment]
@cprybol thanks for opening an issue and I'm really sorry your having problems updating, hopefully we'll be able to get it working shortly :D

@leipert would probably be better placed to answer this (I'm on windows and he's on OSX :D) but it looks like the update can't see you compiler toolchain. Have you updated your beta version of OSX since installing `1.7.0`. If so it may well have changed your installation of Xcode. It would appead that a similar problem appear over on https://github.com/Homebrew/homebrew/issues/40653#issuecomment-124064291. If you havn't already done so it looks like you will need to install and configure Xcode 7 as your default toolchain.

If you have any question about those steps or If you've done that and its still not working please let me know and we'll take it from there :D

**Comment by cprybol** [comment]
@Galadirith Thanks for the explanation and for referencing the issue over on the homebrew channel. It does look like updating to Xcode 7 would fix the issue, but Xcode 7 is only available to enrolled developers (I'm just running the publicly available beta, no paid enrollment necessary). I did install MPP 1.7.0 prior to installing the beta OS, so it looks like I'll just have to wait until the official OS release before I can get access to Xcode 7 and resolve this system conflict. This doesn't seem to be an issue with the MPP 2.0.0 update at all.

Thanks for making this great tool available to the public, and I look forward to updating whenever Xcode 7 gets released!

**Comment by Galadirith** [comment]
@cprybol Thanks so much for your kind words and sorry I couldn't be of more help in this instance. @leipert has worked really hard to try to mitigate installation issues, but clearly their is a wider issue on every platform of getting the right compiler toolchains. Hopefully in the not to distant future we'll be able to do away with any native installation and then we can all celebrate :D
