### ISSUE TITLE
Fails on linux mint (I know why)

### ISSUE THREAD

**Issue by aclarembeau** [Galadirith/markdown-preview-plus#91]
When I tried to install the package on Linux mint, I got the following error: 
```
Installing markdown-preview-plus to /home/aclarembeau/.atom/packages ✗

> oniguruma@4.2.2 install /tmp/apm-install-dir-11582-20374-16y3my4/node_modules/markdown-preview-plus/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma
> node-gyp rebuild

make: entrant dans le répertoire « /tmp/apm-install-dir-11582-20374-16y3my4/node_modules/markdown-preview-plus/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma/build »
  CC(target) Release/obj.target/oniguruma/deps/onig/regcomp.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regenc.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regerror.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regexec.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regext.o
  CC(target) Release/obj.target/oniguruma/deps/onig/reggnu.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regparse.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regposerr.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regposix.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regsyntax.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regtrav.o
  CC(target) Release/obj.target/oniguruma/deps/onig/regversion.o
  CC(target) Release/obj.target/oniguruma/deps/onig/st.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/ascii.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/big5.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/cp1251.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_jp.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_kr.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/euc_tw.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/gb18030.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_1.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_2.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_3.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_4.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_5.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_6.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_7.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_8.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_9.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_10.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_11.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_13.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_14.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_15.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/iso8859_16.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/koi8.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/koi8_r.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/mktable.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/sjis.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/unicode.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf16_be.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf16_le.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf32_be.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf32_le.o
  CC(target) Release/obj.target/oniguruma/deps/onig/enc/utf8.o
  AR(target) Release/obj.target/oniguruma.a
  COPY Release/oniguruma.a
  CXX(target) Release/obj.target/onig_scanner/src/onig-cache.o
make: quittant le répertoire « /tmp/apm-install-dir-11582-20374-16y3my4/node_modules/markdown-preview-plus/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma/build »

> pathwatcher-without-runas@4.5.0 install /tmp/apm-install-dir-11582-20374-16y3my4/node_modules/markdown-preview-plus/node_modules/pathwatcher-without-runas
> node-gyp rebuild

make: entrant dans le répertoire « /tmp/apm-install-dir-11582-20374-16y3my4/node_modules/markdown-preview-plus/node_modules/pathwatcher-without-runas/build »
  CXX(target) Release/obj.target/pathwatcher/src/main.o
make: quittant le répertoire « /tmp/apm-install-dir-11582-20374-16y3my4/node_modules/markdown-preview-plus/node_modules/pathwatcher-without-runas/build »

npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN optional dep failed, continuing fsevents@0.3.8
make: g++: commande introuvable
make: *** [Release/obj.target/onig_scanner/src/onig-cache.o] Erreur 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.16.0-38-generic
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11582-20374-16y3my4/node_modules/markdown-preview-plus/node_modules/highlights/node_modules/first-mate/node_modules/oniguruma
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
make: g++: commande introuvable
make: *** [Release/obj.target/pathwatcher/src/main.o] Erreur 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Linux 3.16.0-38-generic
gyp ERR! command "node" "/usr/share/atom/resources/app/apm/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-11582-20374-16y3my4/node_modules/markdown-preview-plus/node_modules/pathwatcher-without-runas
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
npm ERR! Linux 3.16.0-38-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/aclarembeau/.atom/.apm/.apmrc" "--userconfig" "/home/aclarembeau/.atom/.apmrc" "install" "/tmp/d-11582-20374-1f7cmiz/package.tgz" "--target=0.22.0" "--arch=x64"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! oniguruma@4.2.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oniguruma@4.2.2 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the oniguruma package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls oniguruma
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-11582-20374-16y3my4/npm-debug.log
```
The origin of the problem is that g++ is not installed by default, so I had to download it and the package "build-essential". Maybe, it should be a new dependency for the package?

**Comment by Galadirith** [comment]
Thanks @aclarembeau for posting the issue :D So in our [installation instructions](https://github.com/Galadirith/markdown-preview-plus#installation) we do ask everyone to check that they have the files that [`node-gyp` requires](https://github.com/nodejs/node-gyp#installation). In your case if you look under the *On Unix* bullet point you'll see it does say it needs *A proper C/C++ compiler toolchain, like GCC*, but its great that you managed to figure that out yourself :D

As far as adding it as a dependency for our package, it isn't possible to add compiler toolchains as package dependencies; it would certainly be great if we could :D

Thanks again @aclarembeau and I hope my comments answer your questions. I'll close the issue but please ping me back if you have any other questions/solutions ;D

**Comment by aclarembeau** [comment]
Thank you for that good answer :)
For me, the problem is with the node-gyp requirement. On its website I saw
"C/C++ compiler like gcc". I had already gcc but not g++. It isn't very
clear that C/C++ means C and C++.
(maybe it could also be because English isn't my native tongue and because
I'm lazy when I install something I often just read the bold points/unix
commands ^^).
If the first point was:

   1.

   Make sure node-gyp is installed correctly
   <https://github.com/TooTallNate/node-gyp#installation> with a python 2.7
   version (and Visual Studio 2012 or 2013 if you are on Windows) and with a C
   and C++ compiler toolchain (eg: apt-get install build-essential)

I would not have done that mistake.
Anyway, the package is very good (just a little problem with char encoding
but I'll open a new issue for that :) )
Thank you for your feedback :)

2015-09-03 2:03 GMT+02:00 Edward Fauchon-Jones <notifications@github.com>:

**Comment by Galadirith** [comment]
@aclarembeau Ah I see :D To be fair the wording is actually ambiguous so if I was in a similar position I'm quite certain I would have also made the same mistake :D Thanks again @aclarembeau :D
