### ISSUE TITLE
Updating MPP from 2.0.0 to 2.0.1 fails on Windows 7

### ISSUE THREAD

**Issue by djbucci** [Galadirith/markdown-preview-plus#97]
For some reason, updating from MPP 2.0.0 to 2.0.1 breaks MPP on my system with the following output.

```
> pathwatcher-without-runas@4.5.0 install C:\Users\e309423\AppData\Local\Temp\apm-install-dir-11583-11340-12npq6e\node_modules\markdown-preview-plus\node_modules\pathwatcher-without-runas
> node-gyp rebuild


C:\Users\e309423\AppData\Local\Temp\apm-install-dir-11583-11340-12npq6e\node_modules\markdown-preview-plus\node_modules\pathwatcher-without-runas>node "C:\Users\e309423\AppData\Local\atom\app-1.0.7\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 

> oniguruma@4.2.2 install C:\Users\e309423\AppData\Local\Temp\apm-install-dir-11583-11340-12npq6e\node_modules\markdown-preview-plus\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma
> node-gyp rebuild


C:\Users\e309423\AppData\Local\Temp\apm-install-dir-11583-11340-12npq6e\node_modules\markdown-preview-plus\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma>node "C:\Users\e309423\AppData\Local\atom\app-1.0.7\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild 
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(396,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\e309423\AppData\Local\Temp\apm-install-dir-11583-11340-12npq6e\node_modules\markdown-preview-plus\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma\build\oniguruma.vcxproj]
  regcomp.c
  regenc.c
  regerror.c
  regexec.c
  regext.c
  reggnu.c
  regparse.c
  regposerr.c
  regposix.c
  regsyntax.c
  regtrav.c
  regversion.c
  st.c
  ascii.c
  big5.c
  cp1251.c
  euc_jp.c
  euc_kr.c
  euc_tw.c
  gb18030.c
  iso8859_1.c
  iso8859_2.c
  iso8859_3.c
  iso8859_4.c
  iso8859_5.c
  iso8859_6.c
  iso8859_7.c
  iso8859_8.c
  iso8859_9.c
  iso8859_10.c
  iso8859_11.c
  iso8859_13.c
  iso8859_14.c
  iso8859_15.c
  iso8859_16.c
  koi8.c
  koi8_r.c
  mktable.c
  sjis.c
  unicode.c
  utf16_be.c
  utf16_le.c
  utf32_be.c
  utf32_le.c
  utf8.c
  oniguruma.vcxproj -> C:\Users\e309423\AppData\Local\Temp\apm-install-dir-11583-11340-12npq6e\node_modules\markdown-preview-plus\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma\build\Release\\oniguruma.lib
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V120\Microsoft.CppBuild.targets(396,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\e309423\AppData\Local\Temp\apm-install-dir-11583-11340-12npq6e\node_modules\markdown-preview-plus\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma\build\onig_scanner.vcxproj]
  onig-cache.cc
  onig-result.cc
  onig-reg-exp.cc
  onig-scanner.cc
  onig-scanner-worker.cc
  onig-searcher.cc
  onig-string-context.cc
  unicode-utils-win.cc
     Creating library C:\Users\e309423\AppData\Local\Temp\apm-install-dir-11583-11340-12npq6e\node_modules\markdown-preview-plus\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma\build\Release\onig_scanner.lib and object C:\Users\e309423\AppData\Local\Temp\apm-install-dir-11583-11340-12npq6e\node_modules\markdown-preview-plus\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma\build\Release\onig_scanner.exp
  Generating code
  Finished generating code
  onig_scanner.vcxproj -> C:\Users\e309423\AppData\Local\Temp\apm-install-dir-11583-11340-12npq6e\node_modules\markdown-preview-plus\node_modules\highlights\node_modules\first-mate\node_modules\oniguruma\build\Release\\onig_scanner.node

npm WARN deprecated CSSselect@0.4.1: the module is now available as 'css-select'
npm WARN deprecated CSSwhat@0.4.7: the module is now available as 'css-what'
npm WARN optional dep failed, continuing fsevents@0.3.8
gypnpm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Users\\e309423\\AppData\\Local\\atom\\app-1.0.7\\resources\\app\\apm\\bin\\\\node.exe" "C:\\Users\\e309423\\AppData\\Local\\atom\\app-1.0.7\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "C:\\Users\\e309423\\.atom\\.apm\\.apmrc" "--userconfig" "C:\\Users\\e309423\\.atom\\.apmrc" "install" "C:\\Users\\e309423\\AppData\\Local\\Temp\\d-11583-11340-w2x1y6\\package.tgz" "--target=0.22.0" "--arch=ia32" "--msvs_version=2013"
npm ERR! node v0.10.35
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! pathwatcher-without-runas@4.5.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the pathwatcher-without-runas@4.5.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the pathwatcher-without-runas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls pathwatcher-without-runas
npm ERR! There is likely additional logging output above.
```

**Comment by leipert** [comment]
Which atom version do you have?

**Comment by djbucci** [comment]
Apologies...hit close by accident instead of comment.

This may be linked to [#90](https://github.com/Galadirith/markdown-preview-plus/issues/90)?

**Comment by djbucci** [comment]
1.0.7

**Comment by leipert** [comment]
Could you try it with the newest version, 1.0.11?

**Comment by leipert** [comment]
Also the following output would be nice:
```
apm --version
```
and
```
apm install --check
```


Thank you for your efforts and using markdown-preview-plus.

**Comment by djbucci** [comment]
No problem! So after upgrading to 1.0.11, MPP installs successfully. Opening the preview pane however produces the following error:

---

### Stack Trace

Uncaught TypeError: Cannot read property 'decode' of null

```
At C:\Users\e309423\.atom\packages\markdown-preview-plus\lib\renderer.coffee:145

TypeError: Cannot read property 'decode' of null
  at resolveImagePaths (C:\Users\e309423\.atom\packages\markdown-preview-plus\lib\renderer.coffee:114:23)
  at Function.callbackFunction (C:\Users\e309423\.atom\packages\markdown-preview-plus\lib\renderer.coffee:56:12)
  at handleResponse (C:\Users\e309423\.atom\packages\markdown-preview-plus\lib\pandoc-helper.coffee:133:19)
  at ChildProcess.<anonymous> (C:\Users\e309423\.atom\packages\markdown-preview-plus\node_modules\pdc\pdc.js:65:5)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at maybeClose (child_process.js:997:16)
  at Process.ChildProcess._handle.onexit (child_process.js:1070:5)

```

### Commands

```
     -1:24.5.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  2x -0:06.1.0 core:close (ul.list-inline.tab-bar.inset-panel)
     -0:03.2.0 markdown-preview-plus:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ],
    "disabledPackages": [
      "markdown-preview"
    ]
  },
  "markdown-preview-plus": {
    "enableLatexRenderingByDefault": true,
    "enablePandoc": true,
    "pandocBibliography": true,
    "pandocRemoveReferences": false,
    "breakOnSingleNewline": true
  }
}
```

### Installed Packages

```coffee
# User
language-latex, v0.6.1
latex, v0.25.1
markdown-preview-plus, v2.0.1
markdown-table-formatter, v2.5.3
mathjax-wrapper, v0.1.0
run-in-terminal, v0.4.2
terminal-status, v1.6.8

# Dev
No dev packages
```
---
Checking the APM version and install tools yield the following outputs:
```
> apm --version
apm  1.0.4
npm  2.13.3
node 0.10.40
python 2.7.10
git 1.9.5.github.0
visual studio 2013
```
```
> apm install --check
Checking for native build tools done
```

**Comment by leipert** [comment]
You are trying to render your documents with pandoc?

**Comment by leipert** [comment]
If not please deactivate: "Enable Pandoc"

If yes, please be sure that the full path to pandoc executable is written in
Pandoc Options: Path
Furthermore:
1. Just try restarting atom.
2. Is it failing for every document?

**Comment by djbucci** [comment]
Yeah I'm using pandoc. Writing in the full path to the pandoc executable fixes it. Thanks for your help!

**Comment by leipert** [comment]
Glad I could help. Even if I am not on a Windows System.

**Comment by djbucci** [comment]
*Sigh* I spoke a little prematurely. Placing the full path to pandoc doesn't change anything. The following steps fixes the error for a given atom session:

1) Attempt to render a document with the MPP preview pane open (error is raised).
2) Close MPP preview pane.
3) Disable pandoc rendering
4) Reopen MPP preview pane with pandoc rendering off (no error is raised).
5) Close MPP preview pane and re-enable pandoc rendering.
5) Reopen MPP preview pane with pandoc rendering on (no error is raised)

Once I restart the atom session, the error is raised again.

Also, I notice that this is linked to the presence of images in my MD files.

**Comment by Galadirith** [comment]
I think the problem might possibly be in [`renderer#L114`](https://github.com/Galadirith/markdown-preview-plus/blob/9e6048acca568e1c4d1d7c7218fd9fc6f3a076a8/lib/renderer.coffee#L114). I never conditioned on weather `markdownIt` exists which it won't do if your rendering with Pandoc as we're lazy loading `markdown-it`. Really sorry about that @djbucci but it should be an easy fix :D

**Comment by leipert** [comment]
@Galadirith Will you fix and push a 2.0.2 ?

**Comment by Galadirith** [comment]
@leipert Yeh definitely I'll handle this one. I will push a `2.0.2` but not tonight, most likely tomorrow evening, I don't want to overwhelm users with a flood of versions. And we may well catch a few more by then :D

**Comment by leipert** [comment]
Moved it to it's own issue. #99
